version: '3.4'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
volumes:
  ethchaindnpdappnodeeth_data: {}
  ethchaindnpdappnodeeth_geth: {}
  ethchaindnpdappnodeeth_identity: {}
services:
  ethchain.dnp.dappnode.eth:
    build: ./build
    image: 'ethchain.dnp.dappnode.eth:0.2.18'
    container_name: DAppNodeCore-ethchain.dnp.dappnode.eth
    restart: always
    volumes:
      - 'ethchaindnpdappnodeeth_data:/root/.local/share/io.parity.ethereum'
      - 'ethchaindnpdappnodeeth_geth:/root/.ethereum/'
      - 'ethchaindnpdappnodeeth_identity:/root/identity/'
    environment:
      - EXTRA_OPTS=--warp-barrier 8540000
      - EXTRA_OPTS_GETH
      - DEFAULT_CLIENT=PARITY
    ports:
      - '30303:30303'
      - '30303:30303/udp'
      - '30304:30304/udp'
    dns: 172.33.1.2
    networks:
      network:
        ipv4_address: 172.33.1.6
    logging:
      options:
        max-size: 10m
        max-file: '3'
